export const SET_HEADER_LINKS = 'SET_HEADER_LINKS';
export const SET_NAVBAR_LINKS = 'SET_NAVBAR_LINKS';
export const CHANGE_NAVBAR_ACTIVE = 'CHANGE_NAVBAR_ACTIVE';


// USERS
export const SET_USERS_PURCHASES = 'SET_USERS_PURCHASES';
export const SET_PURCHASE_DETAIL = 'SET_PURCHASE_DETAIL';

// USERS CART PRODUCT
export const SET_CART_PRODUCT = 'SET_CART_PRODUCT';


//SHOP 
export const SET_SHOP_PRODUCTS = 'SET_SHOP_PRODUCTS';
export const SET_SHOP_CATEGORIES = 'SET_SHOP_CATEGORIES';
export const FILTER_PRODUCTS_WITH_CATEGORY_ID = 'FILTER_PRODUCTS_WITH_CATEGORY_ID';
export const FILTER_PRODUCTS_WITH_QUERY = 'FILTER_PRODUCTS_WITH_QUERY';